<a href="https://colab.research.google.com/github/mahekgheewala/ML_Mathematics/blob/main/Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


Creating a Matrix using numpy

In [2]:
# The 2 brackets are the 2 rows of a Matrix
matrix1 = np.array([[2,3], [6,7]])
print(matrix1)

[[2 3]
 [6 7]]


In [5]:
matrix2 = np.array([[10, 34, 33], [12, 34, 33], [12, 33, 2]])
print(matrix2)

[[10 34 33]
 [12 34 33]
 [12 33  2]]


Creating Matrices with random values.

In [6]:
random_matrix = np.random.random((3,3))
print(random_matrix)

[[0.32570417 0.62483015 0.94805079]
 [0.98111137 0.6912482  0.62776971]
 [0.34317233 0.66676733 0.98000342]]


In [7]:
random_matrix2 = np.random.randint(10, 20, (4,5))
# We can also write it as:
# np.random.randiant(100, (2,3))
# Here all the values would be less than 100
print(random_matrix2)

[[17 13 19 15 16]
 [16 10 14 17 11]
 [13 12 13 10 11]
 [14 15 10 12 18]]


Matrix with all the values as 1.

In [9]:
matrix3 = np.ones((2,3))
print(matrix3)

[[1. 1. 1.]
 [1. 1. 1.]]


In above code, all the values is in floating number, now we would create all the values in integer.

In [10]:
matrix3 = np.ones((2,3), dtype=int)
print(matrix3)

[[1 1 1]
 [1 1 1]]


Creating a Null Matrix.

In [11]:
matrix4 = np.zeros((2,3), dtype = int)
print(matrix4)

[[0 0 0]
 [0 0 0]]


Creating a Identity Matrix.

In [13]:
matrix5 = np.eye(3,3, dtype=int)
print(matrix5)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


Transpose of a Matrix.

In [16]:
matrix6 = np.random.randint(10, 30, (2,3))
print(matrix6)
matrix7 = np.transpose(matrix6)
print(matrix7)

[[27 28 12]
 [29 28 10]]
[[27 29]
 [28 28]
 [12 10]]


Matrix Addition / Subtraction.

In [18]:
matrix_a = np.array([[2,3], [10, 9]])
matrix_b = np.array([[20,30], [12, 33]])
print(matrix_a)
print(matrix_b)
print(matrix_a + matrix_b)
print(matrix_a - matrix_b)

[[ 2  3]
 [10  9]]
[[20 30]
 [12 33]]
[[22 33]
 [22 42]]
[[-18 -27]
 [ -2 -24]]


Another way.

In [20]:
a = np.random.randint(20, size=(3,3))
b = np.random.randint(34, size=(3,3))

In [21]:
sum = np.add(a, b)

In [22]:
print(sum)

[[19 36 11]
 [21 50 37]
 [39 18 37]]


In [23]:
diff = np.subtract(a,b)

In [24]:
print(diff)

[[ 13 -12  -1]
 [ 17 -14  -1]
 [ -5  -4  -7]]


Multiply a Matrix by a scalar

In [26]:
x = 5
y = np.random.randint(12, size=(3,3))
print(y)

[[5 0 7]
 [9 6 1]
 [0 6 9]]


In [27]:
product = np.multiply(x,y)
print(product)

[[25  0 35]
 [45 30  5]
 [ 0 30 45]]


Multiplying 2 matrix


In [28]:
c = np.random.randint(5, size=(2,3))
d = np.random.randint(4, size=(3,4))

In [29]:
print(c)

[[1 3 1]
 [3 2 1]]


In [30]:
print(d)

[[1 1 2 2]
 [0 3 0 3]
 [2 1 2 2]]


In [31]:
product1 = np.dot(c,d)
print(product1)

[[ 3 11  4 13]
 [ 5 10  8 14]]


Element wise Matrix Multiplication.

In [36]:
m = np.random.randint(5, size=(2,3))
n = np.random.randint(4, size=(2,3))

In [37]:
print(m)

[[0 3 4]
 [1 2 1]]


In [38]:
print(n)

[[0 2 2]
 [0 2 0]]


In [40]:
product2 = np.multiply(m,n)
print(product2)

[[0 6 8]
 [0 4 0]]
